name: LogBlock
version: '1.20'
author: DiddiZ
website: http://www.diddiz.de/minecraft/
main: de.diddiz.LogBlock.LogBlock
description: Logs blocks.
softdepend: [BukkitContrib, LogBlockQuestioner, Permissions, WorldEdit]
commands:
  lb:
    description: 'LogBlock commands.'
    usage: 'Usage: /<command> help'
    aliases: []