name: LogBlock
version: '1.00rc1'
author: DiddiZ, bootswithdefer
website: http://www.diddiz.de/minecraft/
main: de.diddiz.LogBlock.LogBlock
description: Logs blocks.
commands:
  lb:
    description: 'LogBlock commands.'
    usage: 'Usage: /<command> help'
    aliases: []